export const {
  VITE_BASE_URL: BASE_URL,
  VITE_CHANNELIO_PLUGIN_KEY: CHANNELIO_PLUGIN_KEY,
  VITE_ACCESS_TOKEN: ACCESS_TOKEN,
  VITE_CLIENT_KEY: CLIENT_KEY,
  REACT_APP_SECURE_LOCAL_STORAGE_HASH_KEY: SECURE_KEY
} = import.meta.env;
